// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementApi.Data;

#nullable disable

namespace SchoolManagementApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260113074832_Create")]
    partial class Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagementApi.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Principal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Trinh Van Bo, Hanoi",
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "FPT Polytechnic",
                            Principal = "Vu Chi Thanh"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Times City, Hanoi",
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vinschool",
                            Principal = "Phan Ha Thuy"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Royal City, Hanoi",
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "British Vietnamese International School",
                            Principal = "Milan Gratford"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Hoang Minh Giam, Hanoi",
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hanoi - Amsterdam",
                            Principal = "Tran Thuy Duong"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Nguyen Trai, HCM City",
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Le Hong Phong High School",
                            Principal = "Pham Thi Be Hien"
                        },
                        new
                        {
                            Id = 6,
                            Address = "My Dinh, Hanoi",
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Doan Thi Diem Primary School",
                            Principal = "Nguyen Thi Hien"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Tran Van Bo, Hanoi",
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marie Curie School",
                            Principal = "Nguyen Xuan Khang"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Yen Hoa, Hanoi",
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nguyen Sieu School",
                            Principal = "Nguyen Trong Vinh"
                        },
                        new
                        {
                            Id = 9,
                            Address = "My Dinh 2, Hanoi",
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lomonoxop School",
                            Principal = "Nguyen Phuc Chinh"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Sala, HCM City",
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "VAS - Vietnam Australia School",
                            Principal = "Marcel van Miert"
                        });
                });

            modelBuilder.Entity("SchoolManagementApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SchoolId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anhnv@fpt.edu.vn",
                            FullName = "Nguyen Van Anh",
                            Phone = "0912345678",
                            SchoolId = 1,
                            StudentId = "PH12345"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "binhtt@fpt.edu.vn",
                            FullName = "Tran Thi Binh",
                            Phone = "0922345678",
                            SchoolId = 1,
                            StudentId = "PH12346"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chunglh@vinschool.edu.vn",
                            FullName = "Le Huy Chung",
                            Phone = "0932345678",
                            SchoolId = 2,
                            StudentId = "VIN001"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dungpm@vinschool.edu.vn",
                            FullName = "Pham My Dung",
                            Phone = "0942345678",
                            SchoolId = 2,
                            StudentId = "VIN002"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bachhg@bvis.edu.vn",
                            FullName = "Hoang Gia Bach",
                            Phone = "0952345678",
                            SchoolId = 3,
                            StudentId = "BVIS01"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ducvm@bvis.edu.vn",
                            FullName = "Vu Minh Duc",
                            Phone = "0962345678",
                            SchoolId = 3,
                            StudentId = "BVIS02"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "datdt@ams.edu.vn",
                            FullName = "Do Thanh Dat",
                            Phone = "0972345678",
                            SchoolId = 4,
                            StudentId = "AMS101"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "linhnp@ams.edu.vn",
                            FullName = "Ngo Phuong Linh",
                            Phone = "0982345678",
                            SchoolId = 4,
                            StudentId = "AMS102"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hungdv@lhp.edu.vn",
                            FullName = "Dang Van Hung",
                            Phone = "0992345678",
                            SchoolId = 5,
                            StudentId = "LHP201"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kienbx@lhp.edu.vn",
                            FullName = "Bui Xuan Kien",
                            Phone = "0812345678",
                            SchoolId = 5,
                            StudentId = "LHP202"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "namlh@dtd.edu.vn",
                            FullName = "Ly Hai Nam",
                            Phone = "0822345678",
                            SchoolId = 6,
                            StudentId = "DTD301"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khanhpq@dtd.edu.vn",
                            FullName = "Phan Quoc Khanh",
                            Phone = "0832345678",
                            SchoolId = 6,
                            StudentId = "DTD302"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sontc@mc.edu.vn",
                            FullName = "Trinh Cong Son",
                            Phone = "0842345678",
                            SchoolId = 7,
                            StudentId = "MC401"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "giapvn@mc.edu.vn",
                            FullName = "Vo Nguyen Giap",
                            Phone = "0852345678",
                            SchoolId = 7,
                            StudentId = "MC402"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sonct@ns.edu.vn",
                            FullName = "Cao Thai Son",
                            Phone = "0862345678",
                            SchoolId = 8,
                            StudentId = "NS501"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thuymp@ns.edu.vn",
                            FullName = "Mai Phuong Thuy",
                            Phone = "0872345678",
                            SchoolId = 8,
                            StudentId = "NS502"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tuanha@lom.edu.vn",
                            FullName = "Ha Anh Tuan",
                            Phone = "0882345678",
                            SchoolId = 9,
                            StudentId = "LOM601"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nhungnh@lom.edu.vn",
                            FullName = "Nguyen Hong Nhung",
                            Phone = "0892345678",
                            SchoolId = 9,
                            StudentId = "LOM602"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "quyenl@vas.edu.vn",
                            FullName = "Le Quyen",
                            Phone = "0772345678",
                            SchoolId = 10,
                            StudentId = "VAS701"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tungst@vas.edu.vn",
                            FullName = "Son Tung MTP",
                            Phone = "0782345678",
                            SchoolId = 10,
                            StudentId = "VAS702"
                        });
                });

            modelBuilder.Entity("SchoolManagementApi.Models.Student", b =>
                {
                    b.HasOne("SchoolManagementApi.Models.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("SchoolManagementApi.Models.School", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
